baseURL = 'https://dcrobot-keen.github.io/it-news-mail/'
languageCode = 'ko-kr'
defaultContentLanguage = 'ko-kr'
title = 'IT News Digest'
theme = 'stack'
copyright = "Â© 2025 IT News Digest"

[pagination]
  pagerSize = 10

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
  mainSections = ['posts']
  featuredImageField = 'image'
  rssFullContent = true
  favicon = "/favicon.ico"

  [params.footer]
    since = 2025
    customText = "AI, ë¡œë³´í‹±ìŠ¤, ê°œë°œ ë‰´ìŠ¤ë¥¼ ìš”ì•½í•´ì„œ ì „ë‹¬í•©ë‹ˆë‹¤"

  [params.dateFormat]
    published = "2006-01-02"
    lastUpdated = "2006-01-02 15:04 MST"

  [params.sidebar]
    emoji = "ğŸ“°"
    subtitle = "IT ë‰´ìŠ¤ ìë™í™” ì‹œìŠ¤í…œ"

  [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/dev-keen.png"

  [params.article]
    math = false
    toc = true
    readingTime = true

  [params.article.license]
    enabled = false

  [params.comments]
    enabled = false

[[params.widgets.homepage]]
  type = "categories"
  [params.widgets.homepage.params]
    limit = 10

[[params.widgets.homepage]]
  type = "tag-cloud"
  [params.widgets.homepage.params]
    limit = 50

[[params.widgets.page]]
  type = "toc"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "í™ˆ"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "ì¹´í…Œê³ ë¦¬"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "íƒœê·¸"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "archives"
    name = "ì•„ì¹´ì´ë¸Œ"
    url = "/archives/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    tabWidth = 4

[outputs]
  home = ["HTML", "RSS"]
